## Empirical results

In this section, I present the main empirical findings of the thesis. The objective is to compare different factor models in the context of the cryptocurrency market in order to study the dynamics of cryptocurrency returns. This is carried out within the IPCA framework by estimating models under several specifications: the general IPCA with purely latent factors, models with observable factors and static loadings, and models with observable factors and dynamic loadings (with characteristics instrumenting loadings). Results are reported for different choices of $K$ factors. In addition, I evaluate model performance using the total and predictive scores, both in-sample and out-of-sample. Finally, I examine which cryptocurrency characteristics from the panel data make a significant individual contribution to the overall model fit.

The models and tests described in this section are implemented in Python 3.13.5, using the code provided by Seth Pruitt ^[See https://sethpruitt.net/research/.]. I adapted this code by adding the Wald-type tests with bootstrap procedures, following the implementation in the `ipca` python package of @ipca ^[See https://bkelly-lab.github.io/ipca/.]. All figures are generated using the `matplotlib` package [v. 3.10.3\; @Hunter:2007].

Following @kellyCharacteristicsAre2019, I cross-sectionally standardize the instrument characteristics to mitigate their sensitivity to outliers. Period-by-period, I rank the cryptocurrencies according to each characteristic. Then, I standardize these ranks by dividing them by the number of non-missing observations and subtract 0.5. This transformation maps each characteristic to the interval $[-0.5, 0.5]$, reducing the influence of extreme values while preserving the relative ordering across assets. In addition, all characteristics are lagged and computed up to time $t-1$, i.e., one day prior to the return prediction, and are calculated on a rolling-window basis when necessary. Consequently, the characteristics observed at date $d-1$ determine the exposures associated with the returns realized at date $d$. 

## IPCA asset pricing performance

I estimate the IPCA model with $K = 1, \dots, 6$ factors, considering the restricted ($\Gamma_\alpha = \mathbf{0}$) and the unrestricted specification $\Gamma_\alpha \neq \mathbf{0}$). Panel A in Table \ref{tbl-ipca_results} reports the in-sample performance of the IPCA models estimated at the individual cryptocurrency level ($r_t$). As noted in @sec-methodology, because the IPCA is estimated from a least squares criterion, it targets the total $R$ and the latent factors are optimized to capture systematic risk across assets. Consequently, increasing the number of factors raises the total $R$, as shown in the table: it starts at 3.87% for the one-factor model and reaches 9.07% for the six-factor model, with each extra factor contributing less to the increase. Allowing for $\Gamma_\alpha \neq 0$ further increases the total $R$, nearly doubling the values relative to the restricted model, although the gap narrows as $K$ grows.

Turning to the predictive $R$, the restricted one-factor model shows a notably higher value compared to the unrestricted model, but results are relatively similar across the other specifications. The total $R$ results indicates that anomaly intercepts help explain return variation. However, the minimal increment in predictive $R$ suggests that characteristics, through anomaly intercepts, add little to predicting cryptocurrency returns. We confirm this when looking at Table \ref{tbl-alphatest}, which reports the $p$-values from the asset-pricing test of the null hypothesis $\Gamma_\alpha = \mathbf{0}$. Across all values of $K$, except for the 6-factor model, the null cannot be rejected, indicating that anomaly intercepts are not statistically significant in explaining returns beyond systematic risk exposures.

```{=latex}
\begin{table}[h]
\centering
\small
\caption[IPCA in-sample performance.]%
{%
\textbf{IPCA in-sample performance.}
Panels A and B report total and predictive $R$ (in percent) for the restricted model ($\Gamma_\alpha = 0$) and the unrestricted model ($\Gamma_\alpha \neq 0$) across different values of $K$ using daily data. Results are based on individual cryptocurrencies in Panel A and on characteristic-managed portfolios in Panel B. 
}
\label{tbl-ipca_results}
\vspace{5pt} % extra space between caption and tabular
\begin{tabular}{lccccccc}
\toprule
 &  & \multicolumn{6}{c}{K} \\
\cmidrule(lr){3-8}
 &  & 1 & 2 & 3 & 4 & 5 & 6 \\
\midrule\addlinespace[2.5pt]
\multicolumn{8}{l}{Panel A: Individual cryptocurrencies ($r_t$)} \\[2.5pt]
\midrule\addlinespace[2.5pt]
$R_{\text{total}}$      & $\Gamma_{\alpha} = 0$     & 3.87 & 5.45 & 6.94 & 7.79 & 8.50 & 9.07 \\
                            & $\Gamma_{\alpha} \neq 0$  & 8.11 & 11.72 & 13.27 & 14.45 & 15.30 & 16.00 \\
$R_{\text{pred}}$ & $\Gamma_{\alpha} = 0$     & 1.33 & 1.35 & 1.19 & 1.24 & 1.25 & 1.24 \\
                            & $\Gamma_{\alpha} \neq 0$  & 0.29 & 1.40 & 1.43 & 1.27 & 1.32 & 1.34 \\
\midrule\addlinespace[2.5pt]
\multicolumn{8}{l}{Panel B: Managed portfolios ($x_t$)} \\[2.5pt]
\midrule\addlinespace[2.5pt]
$R_{\text{total}}$      & $\Gamma_{\alpha} = 0$     & 41.98 & 46.18 & 57.62 & 59.05 & 60.68 & 63.19 \\
                            & $\Gamma_{\alpha} \neq 0$  & 78.19 & 87.96 & 88.69 & 90.51 & 90.85 & 91.22 \\
$R_{\text{pred}}$ & $\Gamma_{\alpha} = 0$     & 14.01 & 14.16 & 12.16 & 12.59 & 12.65 & 12.51 \\
                            & $\Gamma_{\alpha} \neq 0$  & 0.96 & 4.09 & 4.17 & 3.73 & 3.84 & 3.85 \\
\bottomrule
\end{tabular}
\end{table}

```

Panel B shows the results of the model implemented at the portfolio level. The results shows that for $K>2$, the IPCA already explains more than $50%$ of the portfolio return variation, reaching a maximum of $63.19%$ for the 6-factor model. In this case, allowing for $\Gamma_\alpha$ also increments significantly the total $R$; nevertheless, the predictive $R$ is much lower. Accounting for an anomaly intercept improves the description of the return variation, but decreases the predicting power of returns. 

Panel B reports the results at the portfolio level ($x_t$). For $K>2$, the IPCA already explains more than 50% of the variation in portfolio returns, reaching a maximum of 63.19% with the six-factor model. Allowing for $\Gamma_\alpha \neq 0$ increases the total $R$ significantly. However, the predictive $R$ is much lower in this case: while including anomaly intercepts improves the fit in terms of return variation, it reduces the model’s predictive power for returns.

```{=latex}
\begin{table}
\centering
\small
\caption[Asset-pricing test]%
{%
\textbf{Asset-pricing test.}
The table reports bootstrapped $p$-values for testing whether anomaly intercepts explain returns beyond systematic risk exposures. Specifically, the null hypothesis $H_{0}: \Gamma_{\alpha} = \mathbf{0}$ is tested against the alternative $H_{1}: \Gamma_{\alpha} \neq \mathbf{0}$, using $b = 1, \dots, 1000$ bootstrap simulations. Rejecting the null indicates that characteristics contribute to expected returns through anomaly intercepts, in addition to their role in determining exposures to risk.
}
\label{tbl-alphatest}
\vspace{5pt} % extra space between caption and tabular
\begin{tabular}{lcccccc}
\toprule
 & \multicolumn{6}{c}{K} \\
\cmidrule(lr){2-7}
 &  1 & 2 & 3 & 4 & 5 & 6 \\
\midrule\addlinespace[2.5pt]
$W_\alpha$ $p$-value  & 0.84 & 0.82 & 0.23 & 0.31 & 0.34 & 0.03 \\
\bottomrule
\end{tabular}
\end{table}
```

## Comparison with other factor models

Next, I compare the performance of the general IPCA models with IPCA models that pre-specify observable factors commonly used in the financial literature. Specifically, I consider models with $K=1,\dots,5$ observable factors. The $K=1$ case corresponds to the CAPM using the market factor (CMKT), $K=2$ adds momentum (MOM), and $K=3$ adds the size factor (SMB) following the cryptocurrency three-factor model of @liuCommonRisk2022, an analogue of the Fama-French three-factor model [@famaCommonRisk1993]. The fourth and fifth model add liquidity (LIQ) and volatility (VOL), respectively.

Following @kellyCharacteristicsAre2019, I estimate two versions of these observable factor models. The first is a standard time-series regression with static loadings estimated asset by asset. The second incorporates cryptocurrency characteristics as instruments for the factor loadings, allowing them to vary over time. To ensure comparability in terms of risk compensation, all models are estimated without an intercept ($\Gamma_\alpha = \mathbf{0}$).

Table \ref{tbl-model_comparison} reports the results. Panel A reproduces the IPCA fits from earlier, Panel B shows results for the observable factor models with static loadings, and Panel C reports results for the models with dynamic loadings. Overall, Panel B shows that static observable factor models explain much less variation in returns compared with IPCA, both for individual cryptocurrencies and for managed portfolios. The dynamic version in Panel C performs better, with explanatory power close to that of the general IPCA. Total $R$ is slightly higher when observable factors are pre-specified, but predictive $R$ is nearly identical. For example, with $K=2$, the dynamic observable model already explains more than 50% of portfolio return variation. However, as with IPCA, predictive $R$ declines as additional factors are added, both at the individual and portfolio level.

```{=latex}
\begin{table}
\centering
\small
\caption[IPCA performance compared with observable factor models]%
{%
\textbf{IPCA performance compared with observable factor models.}
The table reports total and predictive $R$ (in percent) for the IPCA model in Panel A, observable factor models with static loadings (no instruments) in Panel B, and observable factor models with dynamic loadings (with instruments) in Panel C. Results are shown for $K=1,\dots,5$ factors using both individual cryptocurrency returns ($r_t$) and characteristic-managed portfolios ($x_t$). Observable models start with the CAPM using the market factor ($K=1$) and sequentially add momentum, size, liquidity, and volatility, yielding $K$-factor models for $K=1,\dots,5$.
}
\label{tbl-model_comparison}
\vspace{5pt} % extra space between caption and tabular
\begin{tabular}{llccccc}
\toprule
Test assets & Statistic & \multicolumn{5}{c}{K} \\
\cmidrule(lr){3-7}
 &  & 1 & 2 & 3 & 4 & 5 \\
\midrule
\multicolumn{7}{l}{Panel A: IPCA} \\
\midrule
$r_t$ & $R_{\text{total}}$ & 3.87 & 5.45 & 6.94 & 7.79 & 8.50 \\
      & $R_{\text{pred}}$  & 1.33 & 1.35 & 1.19 & 1.24 & 1.25 \\
$x_t$ & $R_{\text{total}}$ & 41.98 & 46.18 & 57.62 & 59.05 & 60.68 \\
      & $R_{\text{pred}}$  & 14.01 & 14.16 & 12.16 & 12.59 & 12.65 \\
%\\[1pt]
\midrule
\multicolumn{7}{l}{Panel B: Observable factors: static loadings} \\
\midrule
$r_t$ & $R_{\text{total}}$ & 0.41 & 1.18 & 1.68 & 1.90 & 1.96 \\
      & $R_{\text{pred}}$  & 0.02 & 0.51 & 0.72 & 0.80 & 0.81 \\
$x_t$ & $R_{\text{total}}$ & 5.31 & 16.75 & 25.04 & 28.59 & 30.10 \\
      & $R_{\text{pred}}$  & 0.03 & 5.62 & 8.44 & 9.50 & 9.60 \\
%\\[1pt]
\midrule
\multicolumn{7}{l}{Panel C: Observable factors: dynamic loadings} \\
\midrule
$r_t$ & $R_{\text{total}}$ & 4.17 & 5.85 & 7.20 & 8.12 & 8.84 \\
      & $R_{\text{pred}}$  & 1.33 & 1.36 & 1.19 & 1.25 & 1.25 \\
$x_t$ & $R_{\text{total}}$ & 44.90 & 50.71 & 59.98 & 61.83 & 63.66 \\
      & $R_{\text{pred}}$  & 14.07 & 14.33 & 12.22 & 12.73 & 12.77 \\
\bottomrule
\end{tabular}
\end{table}

```

Table \ref{tbl-dynamic-models} analyzes the contribution of including observable factors in the general IPCA specification. In addition to pre-specifying observable factors, the IPCA can extract additional latent factors from the panel of cryptocurrency characteristics, with both latent and observable factors instrumented by these characteristics at the individual level. For example, the model with one observable factor and $K=1$ uses the market factor as observable but instruments its loading with asset characteristics, while the model with $K=3$ incorporates two additional latent factors. The row labeled 0 corresponds to the general IPCA, while rows 1, 3, and 5 correspond to models with the 1-, 3-, and 5-factor specifications described earlier. Panel A shows that adding observable factors improves the total $R$, rising from 3.87% to 4.50% when the market factor is added at $K=1$. For larger $K$, more than one observable factor is needed for a noticeable gain in model fit, but the improvements fades beyond three pre-specified factors, suggesting that additional ones are redundant. By contrast, Panel B shows that observable factors have little impact on predictive performance, as results are nearly identical across specifications, indicating that the general IPCA already captures most of the predictive power for cryptocurrency returns.

```{=latex}
\begin{table}
\centering
\small
\caption[IPCA with observable factors]%
{%
\textbf{IPCA with observable factors.}
The table reports total and predictive $R$ (in percent) for different IPCA specifications with varying numbers of latent factors $K$. The row labeled 0 corresponds to the general IPCA, with all $K$ factors latent. Rows labeled 1, 3, and 5 correspond to the CAPM, the cryptocurrency 3-factor model, and the 5-factor model, respectively, while still allowing for $K$ latent factors. All models are estimated without an intercept ($\Gamma_\alpha = \mathbf{0}$) at the individual cryptocurrency level.
}
\label{tbl-dynamic-models}
\vspace{5pt} % extra space between caption and tabular
\begin{tabular}{lcccccc}
\toprule
\multicolumn{1}{c}{Observ.} & \multicolumn{6}{c}{$K$} \\
\cmidrule(lr){2-7}
factors & 1 & 2 & 3 & 4 & 5 & 6 \\
\midrule
\multicolumn{7}{l}{Panel A: Total $R$} \\
\midrule
0 & 3.87 & 5.45 & 6.94 & 7.79 & 8.50 & 9.07 \\ 
1 & 4.17 & 5.73 & 7.01 & 7.86 & 8.56 & 9.12 \\
3 & 4.50 & 5.97 & 7.20 & 8.05 & 8.75 & 9.28 \\
5 & 4.63 & 6.09 & 7.31 & 8.15 & 8.84 & 9.37 \\
\midrule
\multicolumn{7}{l}{Panel B: Predictive $R$} \\
\midrule
0 & 1.33 & 1.35 & 1.19 & 1.24 & 1.25 & 1.24 \\
1 & 1.33 & 1.36 & 1.19 & 1.24 & 1.25 & 1.24 \\
3 & 1.31 & 1.36 & 1.19 & 1.24 & 1.25 & 1.25 \\
5 & 1.30 & 1.36 & 1.19 & 1.25 & 1.25 & 1.25 \\
\bottomrule
\end{tabular}
\end{table}
```

Table \ref{tbl-delta-test} reports hypothesis tests of the incremental explanatory power of including observable factors in the IPCA specification. Specifically, it tests the null $H_0:\Gamma_\delta = \mathbf{0}_{L \times M}$, which tests whether a pre-specified factor $g$ does not improve the overall model fit after controlling for the latent factors. The results show that, at the 5% level, the LIQ and VOL factors consistently provide statistically significant improvements across all $K$ models. SMB becomes significant only in the 5- and 6-factor models, while CMKT is significant for $K=2$ and $K=6$. In contrast to previous findings in the literature [@liuCommonRisk2022; @liuCommonRisk2020], the momentum factor (MOM) does not show statistical significance in any of the models.

```{=latex}
\begin{table}
\centering
\small
\caption[Individual significance tests for observable factors]%
{%
\textbf{Individual significance tests for observable factors.}
The table reports $p$-values from Wald-type tests of the incremental explanatory power of pre-specified observable factors, after controlling for the latent IPCA factors. Results are shown for $K=1,\dots,6$ latent factors. Reported $p$-values test the null hypothesis $H_0:\Gamma_\delta = \mathbf{0}_{L \times M}$, i.e., that the observable factor does not improve model fit once latent IPCA factors are included. Both latent and observable loadings are instrumented with characteristics. Green shading indicates statistical significance at the 5\% level. Tests are based on $b = 1, \dots, 1000$ bootstrap simulations.
}
\label{tbl-delta-test}
\vspace{5pt} % extra space between caption and tabular
\begin{tabular}{lcccccc}
\toprule
\multicolumn{1}{c}{Observ.} & \multicolumn{6}{c}{$K$} \\
\cmidrule(lr){2-7}
factor & 1 & 2 & 3 & 4 & 5 & 6 \\
\midrule
CMKT & 0.093 & \cellcolor{green!20}0.036 & 0.365 & 0.127 & 0.108 & \cellcolor{green!20}0.045 \\
MOM  & 0.937 & 0.998 & 0.976 & 0.789 & 0.316 & 0.131 \\
SMB & 0.907 & 0.803 & 0.341 & 0.068 & \cellcolor{green!20}0.007 & \cellcolor{green!20}0.015 \\
LIQ  & \cellcolor{green!20}0.008 & \cellcolor{green!20}0.010 & \cellcolor{green!20}0.004 & \cellcolor{green!20}0.003 & \cellcolor{green!20}0.000 & \cellcolor{green!20}0.000 \\
VOL  & \cellcolor{green!20}0.033 & \cellcolor{green!20}0.018 & \cellcolor{green!20}0.012 & \cellcolor{green!20}0.011 & \cellcolor{green!20}0.005 & \cellcolor{green!20}0.003 \\
\bottomrule
\end{tabular}
\end{table}
```

## Out-of-sample performance

The previous analysis has been based on in-sample estimates, where IPCA factors and loadings are obtained from the full panel of cryptocurrency returns and evaluated on the same data. However, since good in-sample fits does not generally imply good forecasting ability. For that reason, I analyze the out-of-sample performance of the model specifications discussed earlier.

Following the methodology of Kelly et al. (2019), I implement recursive forecasts to evaluate the out-of-sample performance of the model. At each step, the model is estimated using data available up to time $t$ and then used to predict returns at $t+1$. In this setting, the IPCA model provides $\hat{\Gamma}_{\beta,t}$, which maps characteristics into factor loadings based only on information up to time $t$. Using this estimate, the realized factor return is obtained as
$$
\hat{f}_{t+1,t} = \left( \hat{\Gamma}_\beta' Z_t' Z_t \hat{\Gamma}_\beta \right)^{-1} \hat{\Gamma}_\beta' Z_t' r_{t+1}
$$ 
which, combined with $\hat{\Gamma}_{\beta,t}$, generate the predicted return:
$$
\hat r_{t+1} = Z_t \hat{\Gamma}_{\beta,t} \hat{f}_{t+1,t}.
$$ 
The sample is then expanded to include $t+1$, the model is re-estimated, and returns at $t+2$ are predicted, and so on. The first prediction is made on June 1, 2023, using data from June 1, 2018 to May 31, 2023 as the training sample. This starting point corresponds to about 70% of the available data (1826 days). The recursive procedure continues until July 31, 2025, producing one-step-ahead forecasts for each day. 

```{=latex}
\begin{table}[h]
\centering
\small
\caption[Out-of-sample asset pricing performance]%
{%
\textbf{Out-of-sample asset pricing performance.}
The table reports out-of-sample total and predictive $R^2$ (in percent) for the IPCA model in Panel A, observable factor models with static loadings in Panel B, and with dynamic loadings in Panel C. Results are shown for $K=1,\dots,6$ factors using both individual cryptocurrency returns ($r_t$) and characteristic-managed portfolios ($x_t$). Observable models start with a CAPM using the market factor ($K=1$) and sequentially add momentum, size, liquidity, and volatility ($K=2,\dots,5$). Out-of-sample performance is based on a recursive scheme with an initial training sample from June 1, 2018 to May 31, 2023, and day-by-day forecasts for the remaining period (about 30\%) until July 31, 2025. All values are reported in percent.
}
\label{tbl-oos-comparison}
\vspace{5pt} % extra space between caption and tabular
\begin{tabular}{llcccccc}
\toprule
Test assets & Statistic & \multicolumn{6}{c}{K} \\
\cmidrule(lr){3-8}
 &  & 1 & 2 & 3 & 4 & 5 & 6 \\
\midrule
\multicolumn{8}{l}{Panel A: IPCA} \\
\midrule
$r_t$ & $R_{\text{total}}$ & 2.70  & 3.60  & 4.95   & 5.60  & 6.08  & 6.46 \\
      & $R_{\text{pred}}$  & 0.52  & 0.48  & 0.06   & 0.11  & 0.12  & 0.11 \\
$x_t$ & $R_{\text{total}}$ & 30.50 & 35.07 & 57.41  & 58.31 & 60.00 & 62.34 \\
      & $R_{\text{pred}}$  & -1.86 & -3.14 & -10.34 & -9.43 & -9.07 & -9.24 \\
\midrule
\multicolumn{8}{l}{Panel B: Observable factors: static loadings} \\
\midrule
$r_t$ & $R_{\text{total}}$ & 0.53  & 0.78  & 1.08  & 1.12  & 1.15 & \\
      & $R_{\text{pred}}$  & 0.02  & 0.01  & 0.01  & 0.01  & 0.01 & \\
$x_t$ & $R_{\text{total}}$ & 16.71 & 21.43 & 25.72 & 27.26 & 28.29 & \\
      & $R_{\text{pred}}$  & 0.02  & 0.07  & 0.09  & 0.10  & 0.10 & \\
\midrule
\multicolumn{8}{l}{Panel C: Observable factors: dynamic loadings} \\
\midrule
$r_t$ & $R_{\text{total}}$ & 3.11  & 4.01  & 5.00  & 5.65  & 6.13 & \\
      & $R_{\text{pred}}$  & 0.51  & 0.51  & 0.80  & 0.12  & 0.13 & \\
$x_t$ & $R_{\text{total}}$ & 43.40 & 48.54 & 58.96 & 59.97 & 61.55 & \\
      & $R_{\text{pred}}$  & -2.02 & -2.57 & -9.69 & -8.84 & -8.56 & \\
\bottomrule
\end{tabular}
\end{table}
```

Table \ref{tbl-oos-comparison} report the out-of-sample total and predictive $R$. Overall, although the values are lower, the results are relatively similar to the in-sample fits when looking at the individual cryptocurrency level. The total and predictive $R$ are considerably larger in the dynamic models, both IPCA and with observable factors, compared to the static one, whose predictive $R$ are nearly 0. For IPCA, the total $R$ declines when $K > 2$, while for the dynamic observable factor model this decline occurs when $K > 3$.  The two dynamic models perform similarly overall, except for the observable factor model with $K=3$, which produces a relatively high predictive $R$ of 0.80. At the portfolio level, however, both dynamic models perform poorly, as their predictive $R$ values are negative. This suggests that they fail to capture portfolio returns and that simple mean-based forecasts would provide more better predictions.

## Characteristic contribution and significance

#### Interpreting the role of characteristics on factor loadings

In order to interpret the latent IPCA factors, it is necessary to examine how observable characteristics map into factor exposures. This can be done through the estimated $\Gamma_\beta$ coefficients: each column of the $\Gamma_\beta$ matrix reflects the contribution of individual characteristics to the loadings on a given factor $K$. In addition, grouping characteristics by category helps to understand which type of instruments--such as trading activity, volatility, or liquidity--contribute most to the risk exposures.

I focus on the $K=2$ and $K=4$ IPCA models, as these provided the best overall fit in both the in-sample and out-of-sample analyses. @fig-gammasK2 reports the estimated $\Gamma_\beta$ coefficients for the $K=2$ model (restricted to $\Gamma_\alpha = \mathbf{0}$). The first factor is mainly driven by trading activity and volatility-related characteristics. In particular, its strong loadings on short-term volume and turnover indicate that it captures variation in market activity and liquidity, while additional contributions from volatility and distributional characteristics suggest a broader risk component. By contrast, the second factor loads heavily CAPM alpha, pointing to systematic variation in returns not explained by the standard market risk. This suggests that factor 2 may reflect omitted risks or mispricing. Smaller contributions also come from distribution, trading activity, and volatility characteristics.

![**Characteristic contribution in the 2-factor IPCA model.** The figure shows the $\Gamma_\beta$ coefficient estimates from the model with $K=2$ factors. Characteristics are grouped by category, with each category shown in a different color. The model is estimated without an intercept and at the individual cryptocurrency level.](pictures/gammas_K2.png){#fig-gammasK2 fig-scap="Characteristic contribution in 2-factor model"}

@fig-gammasK4 reports the $\Gamma_\beta$ coefficient estimates for the $K=4$ model. Factor 1 again loads strongly on the CAPM alpha, similar to the second factor in the two-factor model. Factor 2 and 3 share common contributions from volatility, trading activity, and distribution-related characteristics. Factor 4 loads heavily on CAPM beta, giving it the interpretation of a market factor. Across both specifications, the contribution of price-size and liquidity characteristics is very limited, playing only a minor role in determining the risk factor loadings.   

![**Characteristic contribution in the 4-factor IPCA model.** The figure shows the $\Gamma_\beta$ coefficient estimates from the model with $K=4$ factors. Characteristics are grouped by category, with each category shown in a different color. The model is estimated without an intercept and at the individual cryptocurrency level.](pictures/gammas_K4.png){#fig-gammasK4 fig-scap="Characteristic contribution in 4-factor model"}

#### Significant characteristics. Which ones matter?  

In this thesis, I include 41 observable cryptocurrency characteristics to instrument for the factor loadings in the IPCA model. Of course, many more potential characteristics exist [see @bianchiMispricingRiskCompensation2021; @liuCommonRisk2022; @mercikCrosssectionalInteractionsCryptocurrency2025]. @kellyCharacteristicsAre2019 introduce a statistical test in the IPCA framework to analyze the marginal contribution of each individual characteristic to the overall model fit (see @sec-char-test), while controlling for all others. As before, the Beta bootstrap test is computed using $b=1, \dots, 1000$ bootstrap simulations. This test helps to examine whether a certain characteristic is redundant or irrelevant for the asset-pricing model.

@fig-charsheatmap shows which characteristics are statistically significant contributing to the model fit across different $K$ factor specifications. In total, 10 characteristics are significant at the 1% level in at least one specification (beta, retvol, r7_1, r14_1, r30_1, r30_14, alpha, skew_7d, maxret_7d, and miret_7d), and 16 at the 5% level. Most of these belong to the past returns category (6) and the distribution category (4). My findings are consistent with @bianchiMispricingRiskCompensation2021, who also report characteristics such as the CAPM beta, maximum return, and momentum to be statistically significant.  Following @kellyCharacteristicsAre2019, I test whether restricting the model to only the set of significant characteristics produces similar explanatory power as the full model with all 41 characteristics instrumenting the latent factor loadings. As shown in Table \ref{tbl-ipca_signchars}, the restricted model performs nearly the same as the full specification. This result is consistent with @kellyCharacteristicsAre2019, who demonstrate that the IPCA can successfully extract systematic risk exposures from a relatively small number of characteristics, while many others are largely redundant to the model fit.


```{=latex}
\begin{table}[h]
\centering
\small
\caption[IPCA fits using significant instruments]%
{%
\textbf{IPCA fits using significant instruments.}
The table reports total and predictive $R$ (in percent) for the restricted model ($\Gamma_\alpha = 0$) and the unrestricted model ($\Gamma_\alpha \neq 0$) across different values of $K$. Only the ten characteristics found significant at the 1\% level are used as instruments. Results are based on individual cryptocurrency returns.
}
\label{tbl-ipca_signchars}
\vspace{5pt} % extra space between caption and tabular
\begin{tabular}{lccccccc}
\toprule
 &  & \multicolumn{6}{c}{K} \\
\cmidrule(lr){3-8}
 &  & 1 & 2 & 3 & 4 & 5 & 6 \\
\midrule\addlinespace[2.5pt]
$R_{\text{total}}$      & $\Gamma_{\alpha} = 0$     & 3.36 & 4.70 & 5.79 & 6.59 & 7.28 & 7.65 \\
                        & $\Gamma_{\alpha} \neq 0$  & 7.96 & 11.07 & 12.20 & 13.20 & 13.99 & 14.68 \\
$R_{\text{pred}}$       & $\Gamma_{\alpha} = 0$     & 0.99 & 0.80 & 0.94 & 0.97 & 0.97 & 0.96 \\
                        & $\Gamma_{\alpha} \neq 0$  & 0.23 & 1.05 & 0.96 & 1.02 & 1.05 & 1.05 \\
\bottomrule
\end{tabular}
\end{table}

```

![**Significant characteristics**. The figure shows which cryptocurrency characteristics are significant in explaining factor loadings across IPCA models with $K=1,\dots,6$ latent factors in the restricted specification $\Gamma_\alpha = \mathbf{0}$. The null hypothesis is that the coefficients for a characteristic, $\Gamma_{\beta,l}$, are zero, meaning it has no effect after controlling for the other characteristics. Colors indicate significance at the 1%, 5%, and 10% levels based on Wald-type tests.](pictures/chars_heatmap.png){#fig-charsheatmap fig-scap="Significant characteristics"}





