project:
  type: book

book:
  title: "Master Thesis Title"
  author: 
    - name: "Jorge Eduardo Frías Navarrete"
      affiliations: 
        - name: "Vienna University of Economics and Business"
  date: "01 August 2025"
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_literature_review.qmd
    - 03_methodology.qmd
    - 04_data.qmd
    - references.qmd
  output-file: "JorgeFrias_thesis"

bibliography: references.yaml
csl: apa.csl
filters: 
  - parse-latex
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    toc-title: "Table of contents"
    lof: true
    lot: true
    papersize: a4
    fontsize: 11pt
    classoption: [openany]
    number-sections: true
    number-depth: 2
    linkcolor: blue
    fig-pos: "h"
    geometry:
      - left=3cm
      - right=2.5cm
      - top=3cm
      - bottom=3cm
      #- showframe

    include-in-header:
      text: |
        \usepackage{amsmath,amssymb}
        \usepackage{unicode-math}
        \setmathfont{Latin Modern Math}
        \usepackage{booktabs, caption, longtable, colortbl, array}
        \usepackage{enumitem}
        \setlist[description]{nosep,style=multiline,leftmargin=3.5cm,font=\normalfont\textsf}
        
        \PassOptionsToPackage{list=true}{subcaption}    % fix fig-scap in list of figs. 
        
        %% To prevent hyphenation
        \tolerance=1
        \emergencystretch=\maxdimen
        \hyphenpenalty=10000
        \hbadness=10000
        %% END hyphenation
        
        \usepackage{geometry}
        \usepackage[T1]{fontenc} 
        \usepackage[utf8]{inputenc}
        \usepackage[ngerman,english]{babel}
        \usepackage{setspace}
        \usepackage{titling}
        \usepackage{parskip}
        \usepackage{helvet}
        \renewcommand{\familydefault}{\sfdefault} % Use sans-serif
        \renewcommand{\bfdefault}{b}      % <-- key: make \textbf use 'b'
        \usepackage{graphicx}
        \usepackage{xcolor}
        \usepackage[font=footnotesize,labelfont={bf, footnotesize}]{caption}
        \captionsetup{
          format=plain,                % no hanging indent
          justification=justified     % full-width text
        }
        
        \setlength{\droptitle}{-5em}
        \onehalfspacing
    template-partials: 
      - before-body.tex



