project:
  type: book

book:
  title: "Edit: Master Thesis Title"
  author:
    - name: 
        given: "Jorge Eduardo"
        family: "Frías Navarrete"
      affiliations:
        - name: "Vienna University of Economics and Business"
  date: "04 September 2025"  #last-modified
  date-format: "MMMM DD, YYYY"
  chapters:
    #- abstract.qmd
    - index.qmd
    - 01_intro.qmd
    #- 02_literature_review.qmd
    - 03_methodology.qmd
    - 04_data.qmd
    - 05_results.qmd
    - 06_conclusion.qmd
    - references.qmd
  appendices:
    - appendix.qmd
  output-file: "JorgeFrias_thesis"
  
bibliography: 
  - references.yaml
  - software_references.bib
csl: apa.csl
filters: 
  - parse-latex
keep-tex: true
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook
    classoption: [openany]
    #documentclass: article  # For two-sided. Single-side: scrreprt
    #top-level-division: section # for scrartcl
    toc: true
    toc-depth: 0
    toc-title: "Table of contents"
    lof: true
    lot: true
    papersize: a4
    fontsize: 12pt
    number-sections: true
    number-depth: 2
    #toccolor: black
    colorlinks: true
    linkcolor: blue
    link-citations: true
    fig-pos: "h"
    geometry:
      - left=3cm
      - right=2.5cm
      - top=3cm
      - bottom=3cm
      #- showframe

    include-in-header:
      text: |
        \usepackage{subcaption}
        \captionsetup[subfigure]{list=false}
        % \AddToHook{cmd/section/before}{\clearpage}  % new page for each section for articles
        
        % make all sectioning heads (chapter/section/subsection/…) serif for srcbook
        \setkomafont{disposition}{\normalfont\bfseries\rmfamily}
        
        \usepackage{hyperref}
        \usepackage[nameinlink, capitalise, noabbrev]{cleveref} % \cref{_label_} to link the label and section number 
        
        %\usepackage{multirow}
        %\usepackage{float}
        %\usepackage{pdflscape}
        %\usepackage{tabu}
        \usepackage{makecell}
        \usepackage{threeparttable}
        \usepackage{adjustbox} 
        \usepackage{amsmath,amssymb}
        \usepackage{unicode-math}
        \setmathfont{Latin Modern Math}
        \usepackage{booktabs, caption, longtable, colortbl, array}
        \usepackage{enumitem}
        % \usepackage{float}  % for \begin{table}[h] ? check
        % \setlist[description]{nosep,style=multiline,leftmargin=3.5cm,font=\normalfont\textsf}
        
        \PassOptionsToPackage{list=true}{subcaption}    % fix fig-scap in list of figs. 
        
        %% To prevent hyphenation
        %\tolerance=1
        %\emergencystretch=\maxdimen
        %\hyphenpenalty=10000
        %\hbadness=10000
        %% END hyphenation
        
        \usepackage{geometry}
        \usepackage[T1]{fontenc} 
        \usepackage[utf8]{inputenc}
        \usepackage[english]{babel}
        \usepackage{setspace}
        \usepackage{titling}
        \usepackage{parskip}
        % \usepackage{helvet}
        % \renewcommand{\familydefault}{\sfdefault} % Use sans-serif
        \renewcommand{\bfdefault}{b}      % <-- key: make \textbf use 'b'
        \usepackage{graphicx}
        \usepackage{xcolor}
        \usepackage[font=footnotesize,labelfont={bf, footnotesize}]{caption}
        \captionsetup{
          format=plain,                % no hanging indent
          justification=justified     % full-width text
        }
        
        \setlength{\droptitle}{-5em}
        \onehalfspacing
    template-partials: 
      - before-body.tex
      - toc.tex



